services:
  app:
    build:
      context: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - .:/src
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - default
volumes:
  node_modules: